name: Relay (every 5 minutes)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      GH_API: https://api.github.com
      OWNER: ${{ secrets.TARGET_OWNER }}
      REPO: ${{ secrets.TARGET_REPO }}
      WORKFLOW_FILE: ${{ secrets.TARGET_WORKFLOW }}
      REF: ${{ secrets.TARGET_REF }}
    steps:
      - name: Dispatch LandsAlert workflow (private)
        shell: bash
        run: |
          set -euo pipefail
          endpoint="$GH_API/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_FILE/dispatches"
          body=$(jq -n --arg ref "$REF" '{ref: $ref}')
          http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -X POST "$endpoint" \
            -H "Authorization: Bearer ${{ secrets.LANDSALERT_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$body")
          if [ "$http_code" != "204" ]; then
            echo "Dispatch failed with HTTP $http_code"
            exit 1
          fi
